
services:
  mysql-profile:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin123admin
      MYSQL_DATABASE: ProfileService
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  profile-app:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      mysql-profile:
        condition: service_healthy

